// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TasksColumns holds the columns for the "tasks" table.
	TasksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "done", Type: field.TypeBool, Default: false},
	}
	// TasksTable holds the schema information for the "tasks" table.
	TasksTable = &schema.Table{
		Name:       "tasks",
		Columns:    TasksColumns,
		PrimaryKey: []*schema.Column{TasksColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "email", Type: field.TypeString, Unique: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// UserTasksColumns holds the columns for the "user_tasks" table.
	UserTasksColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeInt},
		{Name: "task_id", Type: field.TypeInt},
	}
	// UserTasksTable holds the schema information for the "user_tasks" table.
	UserTasksTable = &schema.Table{
		Name:       "user_tasks",
		Columns:    UserTasksColumns,
		PrimaryKey: []*schema.Column{UserTasksColumns[0], UserTasksColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_tasks_user_id",
				Columns:    []*schema.Column{UserTasksColumns[0]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "user_tasks_task_id",
				Columns:    []*schema.Column{UserTasksColumns[1]},
				RefColumns: []*schema.Column{TasksColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TasksTable,
		UsersTable,
		UserTasksTable,
	}
)

func init() {
	UserTasksTable.ForeignKeys[0].RefTable = UsersTable
	UserTasksTable.ForeignKeys[1].RefTable = TasksTable
}
